### ISSUE TITLE
Can Pirads score of each findings be provided?

### ISSUE THREAD

**Issue by blacksino** [rcuocolo/PROSTATEx_masks#18] opened 2021-08-18 05:27 UTC

**Comment by rcuocolo** [comment] 2021-08-18 09:17
Duplicate of #5. 

Unfortunately, there is no sure way to assign PI-RADS scores on a lesion-by-lesion basis. We only know that all PROSTATEx2 lesions were assigned a score of at least 3. More details are available in #5.

**Closed as completed by rcuocolo** 2021-08-18 09:17 UTC
