### ISSUE TITLE
ADC mask slice order is inverted/flipped according to the ADC dicom slices

### ISSUE THREAD

**Issue by enliden1** [rcuocolo/PROSTATEx_masks#11] opened 2021-04-29 08:37 UTC
I'm experience that the ADC mask slice order is inverted relative to the ADC dicom files. 

**Let us take ProstateX-0151-Finding2 for example:**
ADC MASK: ProstateX-0151-Finding2-ep2d_diff_tra_DYNDIST_ADC0_ROI.nii
ADC DICOM: 7.000000-ep2ddifftraDYNDISTADC-75959/1-01.dcm  -->  1-23.dcm

Both has 23 slices. From my experience it looks like ADC MASK lesion in slice 8 does not correspond to the slice 8 in ADC DICOM, but rather it correspond to the slice 15 (23-8=15). And that is for every ADC mask lesion examples.  So the order is flipped, or inverted. 

Can you confirm this?

**Comment by rcuocolo** [comment] 2021-04-29 09:59
Duplicate of  #9. I will answer there for both.

**Closed as completed by rcuocolo** 2021-04-29 09:59 UTC
