### ISSUE TITLE
Varying T2WI sequence used for drawing prostate/zonal masks and lesion masks

### ISSUE THREAD

**Issue by pritesh-mehta** [rcuocolo/PROSTATEx_masks#12] opened 2021-04-30 18:31 UTC
Hi Renato,

The prostate/zonal mask for PROSTATEx-0102 uses T2WI sequence 9 for reference, while the lesion mask uses T2WI sequence 5 for reference. Sequences 5 and 9 have different shapes (and therefore the masks drawn using them also), which is causing me some problems, since I use both zonal and lesion masks simultaneously for training my system. Could the prostate/zonal masks be drawn using the same sequence used when drawing the lesion masks? My checks tell me this issue exists for the following cases:

102, 141, 147, 153, 160, 165, 166, 168, 173, 181.

There may be more cases where different T2 sequences were used for drawing prostate/zonal masks and lesion masks, but  the ones highlighted above are the specific cases where differences in shape are causing issue.

**Comment by rcuocolo** [comment] 2021-05-03 12:52
Duplicate of #10.
Unfortunately this situation has arisen as the two annotation processes were conducted at different times (even if by the same readers) and in some cases different axial T2w images were employed. Currently, I do not have the time/personnel required to perform new segmentations for these cases at this moment.

**Closed as completed** 2021-06-04 12:11 UTC
